yao_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - yao_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      yao_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    yao_joint: {p: 10000, d: 50, i: 1, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 1
  allow_partial_joints_goal: True

leg1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - rightleg_joint1
     - leftleg_joint1
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      rightleg_joint1: {trajectory: 0.1, goal: 0.1}
      leftleg_joint1: {trajectory: 0.1, goal: 0.1}
  gains:
    rightleg_joint1: {p: 10000, d: 50, i: 1, i_clamp: 1}
    leftleg_joint1: {p: 10000, d: 50, i: 1, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 1
  allow_partial_joints_goal: True

leg2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - rightleg_joint2
     - leftleg_joint2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      rightleg_joint2: {trajectory: 0.1, goal: 0.1}
      leftleg_joint2: {trajectory: 0.1, goal: 0.1}
  gains:
    rightleg_joint2: {p: 8000, d: 25, i: 1, i_clamp: 1}
    leftleg_joint2: {p: 8000, d: 25, i: 1, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 1
  allow_partial_joints_goal: True


head_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - dt_joint
     - pt_joint
     - yt_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      dt_joint: {trajectory: 0.1, goal: 0.1}
      pt_joint: {trajectory: 0.1, goal: 0.1}
      yt_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    dt_joint: {p: 100, d: 1, i: 0, i_clamp: 1}
    pt_joint: {p: 100, d: 1, i: 0, i_clamp: 1}
    yt_joint: {p: 100, d: 1, i: 0, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 1
  allow_partial_joints_goal: True